# Everything in this file will resolve to a secret.yaml used in Kubernetes
# This enables us to have clear separation of which parts of application.yaml should be encrypted
# For local development, secrets can be defined in plain text in `src/test/resources/skaffold.properties`

app:
  secret-key: ${appSecretKey}
